package com.letianpai.robot.desktop.utils

object AppTagConsts {
    /**Services that need to be started to take a picture */
    const val TAG_NAME_TIME: String = "time"
    const val TAG_NAME_PET: String = "pet"
    const val TAG_NAME_ALBUM: String = "album"
    const val TAG_NAME_APHORISMS: String = "aphorisms"
    const val TAG_NAME_VOICE_MEMO: String = "voicememo"
    const val TAG_NAME_REMINDER: String = "health_reminder"
    const val PACKAGE_APP_NAME_SPECTRUM: String = "spectrum"
    const val PACKAGE_NAME_EXPRESSION: String = "expression"
    const val TAG_AI_PACKAGE_NAME: String = "ai_voice_engine"
    const val ALARM_PACKAGE_NAME: String = "alarmnotice"
    const val WEATHER_PACKAGE_NAME: String = "weather"
    const val PACKAGE_NAME_COMMEMORATION: String = "anniversary"
    const val PACKAGE_NAME_LAMP: String = "marquee"
    const val PACKAGE_NAME_CUSTOM: String = "display"
    const val PACKAGE_NAME_NEWS: String = "news"
    const val PACKAGE_NAME_WORDS: String = "memorize"
    const val PACKAGE_NAME_MESSAGE: String = "message"
    const val STOCK_PACKAGE_NAME: String = "stock"
    const val PACKAGE_NAME_FANS: String = "fans"
    const val PACKAGE_APP_NAME_MEDITATION: String = "meditation"
    const val TAG_NAME_EVENT_COUNT_DOWN: String = "todo"
    const val PACKAGE_APP_NAME_REMINDER: String = "reminder"
    const val PACKAGE_NAME_APP_STORE: String = "appstore"
    const val PACKAGE_NAME_FIST_PALM_GAME: String = "fistpalmgame"
    const val PACKAGE_APP_NAME_POMO: String = "pomodoro"
    const val PACKAGE_NAME_VIDEO_CALL: String = "video_call"
    const val PACKAGE_NAME_REMOTE_CONTROL: String = "remote_control"
    const val PACKAGE_NAME_REMOTE: String = "remote"
    const val TAKEPHOTO_PACKAGE_NAME: String = "camera"
    const val TAG_NAME_GEEUI_SETTINGS: String = "setting"
    const val PACKAGE_NAME_GEEUI_DOWNLOADER: String = "downloader"
    const val PACKAGE_NAME_GEEUI_LOCAL_DOWNLOADER: String = "local_downloader"
    const val TAG_NAME_VIDEO_PLAYER: String = "videoplayer"
    const val TAG_NAME_BLUETOOTH_SPEAKER: String = "bluetooth_speaker"
    const val TAG_NAME_TIME_COUNTDOWN: String = "time_countdown"
    const val TAG_NAME_HOME_NOTIFICATION: String = "notification"
    const val TAG_NAME_HOME_AI_SKILL: String = "ai_skill"
    const val TAG_NAME_ALARM: String = "alarm"
    const val TAG_NAME_MY_MUSIC: String = "my_music"
    const val TAG_NAME_GUIDE: String = "guide"
    const val TAG_NAME_FANS_SHOW: String = "fans_show" // meditation
}
